export const data = [
    {
        "id": 1,
        "fullName": "Jenny Chan",
        "address": "3 waterfoot road",
        "phoneNumber": "333-962-7516",
        "email": "jenny.chan@email.com"
    },
    {
        "id": 2,
        "fullName": "Jessica warren",
        "address": "4 tall town",
        "phoneNumber": "011-211-7516",
        "email": "jessica.warren@email.com"
    },
    {
        "id": 3,
        "fullName": "Tony Frank",
        "address": "11 lesly road",
        "phoneNumber": "788-962-7516",
        "email": "tony.frank@email.com"
    },
    {
        "id": 4,
        "fullName": "Jeremy Clark",
        "address": "333 miltown manor",
        "phoneNumber": "011-962-111",
        "email": "jeremy.clark@email.com"
    },
    {
        "id": 5,
        "fullName": "Raymond Edwards",
        "address": "99 blue acres",
        "phoneNumber": "3231-962-7516",
        "email": "raymon.edwards@email.com"
    }
]

export const poolData = [
    {
        "id": 2180,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": '',
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-24",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_JYFkP44.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2152,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_WREqqwa_nRi0hYP.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2151,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_WREqqwa_uGcALVM.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2150,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": null,
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": "www.linkedin.com/in/prashanth-",
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/9._Prashanth_Ravichandran_22S6W4a.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2149,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": null,
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": "www.linkedin.com/in/",
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/8._Richardson_jebasundar_0aGlshB.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2148,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_WREqqwa_eb64aBA.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2147,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_WREqqwa.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2146,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Job Title",
        "last_name": null,
        "email": null,
        "contact": "",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "HTML5, jQuery, AJAX, Dojo, XML, JavaScript, HTML, CSS, Dojo, JQuery, JavaScript, HTML5, CSS3, JavaScript, HTML, CSS, JQuery, Javascript",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/UI_Developer_Fct1rP3.docx",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2144,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Nalini Kanta",
        "last_name": null,
        "email": "nalini71@gmail.com",
        "contact": "7093700790",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "PL/SQL, Oracle, Core Java, Hadoop, Hive, Pig, Spark, MapReduce, Impala, Python, Toad, Ubuntu, CentOS, Hadoop, Hive, Impala, Python, Pig, python, Python, Hadoop, Hive, Python, Hadoop, Hive",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/cv310308_1_0_hema_EGiSQEG.doc",
        "applicant": null,
        "zita_match": null
    },
    {
        "id": 2143,
        "can_source_id": 1,
        "client_id_id": 403,
        "candidate_id_id": null,
        "job_type_id": null,
        "first_name": "Can Join",
        "last_name": null,
        "email": "srinivas.boppa117@gmal.com",
        "contact": "7288960345",
        "linkedin_url": null,
        "work_exp": null,
        "relocate": null,
        "qualification": null,
        "exp_salary": null,
        "job_title": null,
        "candi_ref_id": null,
        "skills": "Windows, Ubuntu, Centos, MySQL, Tomcat, Git, Maven, AWS",
        "location": null,
        "created_at": "2021-11-12",
        "updated_by": "santhiya K",
        "resume_file": "candidate_resume/clg_449788_-_Hema_Tested.doc",
        "applicant": null,
        "zita_match": 9
    }
]
